<?php

//REQUEST TYPES
define('REQUEST_GET_CLIENT_IDENTIFIER', 'GET_CLIENT_IDENTIFIER');
define('REQUEST_CLIENT_CREATE_CHAT', 'CLIENT_CREATE_CHAT');
define('REQUEST_CLIENT_SEND_CHAT_MESSAGE', 'CLIENT_CHAT_SEND_MESSAGE');
define('REQUEST_CLIENT_CHECK_CHAT_MESSAGE', 'CLIENT_CHAT_CHECK_MESSAGE');





//RESPONSE TYPES
define('RESPONSE_CLIENT_INDENTIFIER', 'CLIENT_INDENTIFIER');
define('RESPONSE_CLIENT_CREATE_CHAT', 'CLIENT_CHAT');
define('RESPONSE_CLIENT_SEND_CHAT_MESSAGE', 'CLIENT_CHAT_SENT_MESSAGE');
define('RESPONSE_CLIENT_CHECK_CHAT_MESSAGE', 'CLIENT_CHAT_MESSAGES');



?>