<?php

//REQUEST TYPES
define('REQUEST_GET_CLIENT_IDENTIFIER', 'GET_CLIENT_IDENTIFIER');
define('REQUEST_CLIENT_CREATE_CHAT', 'CLIENT_CREATE_CHAT');




//RESPONSE TYPES
define('RESPONSE_CLIENT_INDENTIFIER', 'CLIENT_INDENTIFIER');
define('RESPONSE_CLIENT_CHAT', 'CLIENT_CHAT');




?>